**Naive Bayes Tutorial Part 1: Predicting survival from titanic crash**

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [ ]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)

In [ ]:
inputs = df.drop('Survived',axis='columns')
target = df.Survived

In [ ]:
#inputs.Sex = inputs.Sex.map({'male': 1, 'female': 2})

In [ ]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

   female   male
0   False   True
1    True  False
2    True  False

In [ ]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

   Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False

**I am dropping male column as well because of dummy variable trap theory. One column is enough to repressent male vs female**

In [ ]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

   Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True

In [ ]:
inputs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Pclass  891 non-null    int64
 1   Age     891 non-null    float64
 2   Fare    891 non-null    float64
 3   female  891 non-null    bool
dtypes: bool(1), float64(2), int64(1)
memory usage: 21.9 KB

In [ ]:
inputs.Age = inputs.Age.fillna(inputs.Age.median())
inputs.head(10)

   Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True
3       1  35.0  53.1000    True
4       3  35.0   8.0500   False
5       3  28.0   8.4583   False
6       1  54.0  51.8625   False
7       3   2.0  21.0750   False
8       3  27.0  11.1333    True
9       2  14.0  30.0708    True

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [ ]:
model.fit(X_train,y_train)

GaussianNB()

In [ ]:
model.score(X_test,y_test)

0.7835820895522388

In [ ]:
X_test[0:10]

     Pclass   Age     Fare  female
434       1  50.0  55.9000   False
6         1  54.0  51.8625   False
436       3  21.0  34.3750    True
3         1  35.0  53.1000    True
465       3  38.0   7.0500   False
381       3   1.0  15.7417    True
630       1  80.0  30.0000   False
571       1  53.0  51.4792    True
116       3  70.5   7.7500   False
699       3  42.0   7.6500   False

In [ ]:
y_test[0:10]

434    0
6      0
436    0
3      1
465    0
381    1
630    1
571    1
116    0
699    0
Name: Survived, dtype: int64

In [ ]:
model.predict(X_test[0:10])

array([0, 0, 1, 1, 0, 1, 0, 1, 0, 0])

In [ ]:
model.predict_proba(X_test[:10])

array([[0.68857739, 0.31142261],
       [0.71192747, 0.28807253],
       [0.40798511, 0.59201489],
       [0.06483677, 0.93516323],
       [0.97037646, 0.02962354],
       [0.33260623, 0.66739377],
       [0.69869303, 0.30130697],
       [0.06425242, 0.93574758],
       [0.95648859, 0.04351141],
       [0.97049403, 0.02950597]])

**Calculate the score using cross validation**

In [ ]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.688     , 0.768     , 0.776     , 0.79032258, 0.84677419])