In [1]:
import pandas as pd

sheet_id = "1RVnUAGVsr4lrt7nZ2WOq2hFkj7gFcRef"
sheet_name = "Orders"  # or the visible tab name

url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"
df = pd.read_csv(url)

df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11-08-2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11-08-2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,06-12-2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10-11-2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10-11-2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,01-21-2014,23/1/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180.0,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,02-26-2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,02-26-2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,02-26-2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,05-04-2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683.0,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [2]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [3]:
df["Region"].unique()

array(['South', 'West', 'Central', 'East'], dtype=object)

LEVEL 1

In [4]:
#Q1
df1=df[df["Region"] == "South"]
df1[["Order ID","Order Date","Sales","Profit","Region"]].sort_values(by="Sales",ascending=False)

            Order ID  Order Date      Sales     Profit Region
2697  CA-2014-145317  03-18-2014  22638.480 -1811.0784  South
8488  CA-2016-158841  02-02-2016   8749.950  2799.9840  South
683   US-2017-168116  11-04-2017   7999.980 -3839.9904  South
509   CA-2015-145352  03-16-2015   6354.950  3177.4750  South
4297  CA-2017-129021  08-23-2017   4367.896   327.5922  South
...              ...         ...        ...        ...    ...
8317  CA-2017-130904  04-11-2017      1.752     0.1533  South
7900  CA-2017-128363  08-13-2017      1.584     0.4752  South
6597  CA-2014-169257  06-06-2014      1.365    -0.9100  South
9382  CA-2014-154158  12-23-2014      1.344     0.5040  South
2605  CA-2014-112718  12-16-2014      1.167    -0.8558  South

[1620 rows x 5 columns]

In [5]:
#Q2
df1=df[df["Profit"] < 0]
df1[["Category","Sub-Category","Sales","Profit"]].sort_values(by="Profit",ascending=True)

             Category Sub-Category     Sales     Profit
7772       Technology     Machines  4499.985 -6599.9780
683        Technology     Machines  7999.980 -3839.9904
9774  Office Supplies      Binders  2177.584 -3701.8928
3011       Technology     Machines  2549.985 -3399.9800
4991  Office Supplies      Binders  1889.990 -2929.4845
...               ...          ...       ...        ...
4660       Technology  Accessories    27.552    -0.3444
7413        Furniture  Furnishings    13.592    -0.3398
1566       Technology  Accessories    21.480    -0.2685
1496  Office Supplies      Storage    16.784    -0.2098
3228       Technology  Accessories     7.160    -0.0895

[1871 rows x 4 columns]

In [6]:
#Q3
df2 = df[(df["Sales"]>500) & (df["Segment"]=="Consumer")]
df2["Order Date"] = pd.to_datetime(df2["Order Date"])
df2[["Order Date", "Customer Name", "Segment", "Sales"]].sort_values("Order Date").tail()

/tmp/ipykernel_8562/2523053672.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Order Date"] = pd.to_datetime(df2["Order Date"])

     Order Date     Customer Name   Segment     Sales
2728 2017-12-22     Sally Knutson  Consumer   629.958
144  2017-12-22    Sandra Glassco  Consumer   839.430
2056 2017-12-22  Theone Pippenger  Consumer  1586.690
2481 2017-12-24        Alan Hwang  Consumer  1003.620
7632 2017-12-29  Katherine Hughes  Consumer  1207.840

In [7]:
#Q4
df4 = df[df["State"] == "California"]
df4[["State", "City", "Sales", "Profit"]].sort_values("Profit", ascending =False)

           State           City     Sales     Profit
8858  California     Sacramento  5083.960  1906.4850
3273  California    Los Angeles  3359.952  1049.9850
4619  California    Los Angeles  2879.952  1007.9832
3983  California    Los Angeles  2799.960   944.9865
9929  California  San Francisco  2799.960   944.9865
...          ...            ...       ...        ...
1505  California    Los Angeles  1004.976  -175.8708
3480  California  San Francisco  1421.664  -195.4788
557   California    Los Angeles  1335.680  -217.0480
2539  California  San Francisco  1348.704  -219.1644
3770  California  San Francisco  2003.520  -325.5720

[2001 rows x 4 columns]

In [8]:
#Q5
df[df["Discount"]>0.3][["Category", "Sales", "Quantity"]].sort_values("Sales", ascending=False)

             Category      Sales  Quantity
2697       Technology  22638.480         6
6425       Technology   8399.976         4
165        Technology   8159.952         8
683        Technology   7999.980         4
7772       Technology   4499.985         5
...               ...        ...       ...
2106  Office Supplies      0.876         1
4711  Office Supplies      0.852         1
8658  Office Supplies      0.836         1
9292  Office Supplies      0.556         1
4101  Office Supplies      0.444         1

[1166 rows x 3 columns]

In [9]:
#Q6
df[df["Category"] == "Technology"][["Sub-Category", "Sales", "Profit"]].sort_values("Profit", ascending=False)

     Sub-Category      Sales     Profit
6826      Copiers  17499.950  8399.9760
8153      Copiers  13999.960  6719.9808
4190      Copiers  10499.970  5039.9856
2623      Copiers  11199.968  3919.9888
8488     Machines   8749.950  2799.9840
...           ...        ...        ...
2697     Machines  22638.480 -1811.0784
3151     Machines   1799.994 -2639.9912
3011     Machines   2549.985 -3399.9800
683      Machines   7999.980 -3839.9904
7772     Machines   4499.985 -6599.9780

[1847 rows x 3 columns]

In [10]:
#Q7
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["year"]=df["Order Date"].dt.year
df[df["year"] == 2017][["Region", "Category", "Sales", "Profit"]].sort_values("Profit")

       Region         Category      Sales     Profit
683     South       Technology   7999.980 -3839.9904
3011     West       Technology   2549.985 -3399.9800
4991  Central  Office Supplies   1889.990 -2929.4845
5310  Central  Office Supplies   1525.188 -2287.7820
2928    South  Office Supplies   1633.188 -1306.5504
...       ...              ...        ...        ...
8858     West  Office Supplies   5083.960  1906.4850
6520  Central  Office Supplies   5443.960  2504.2216
2623     East       Technology  11199.968  3919.9888
4190     East       Technology  10499.970  5039.9856
8153     West       Technology  13999.960  6719.9808

[3312 rows x 4 columns]

In [11]:
#Q8
df[df["Profit"] < -100][["Customer Name", "Segment", "Sales", "Profit"]].sort_values("Profit")

           Customer Name      Segment     Sales     Profit
7772       Cindy Stewart     Consumer  4499.985 -6599.9780
683       Grant Thornton    Corporate  7999.980 -3839.9904
9774         Luke Foster     Consumer  2177.584 -3701.8928
3011      Sharelle Roach  Home Office  2549.985 -3399.9800
4991       Henry Goldwyn    Corporate  1889.990 -2929.4845
...                  ...          ...       ...        ...
231   Christopher Schild  Home Office   233.860  -102.0480
8623         Fred McMath     Consumer   121.104  -100.9200
1648        Sarah Foster     Consumer   121.104  -100.9200
3673   Eugene Hildebrand  Home Office   121.104  -100.9200
2537         Seth Vernon     Consumer   431.976  -100.7944

[311 rows x 4 columns]

In [12]:
#Q9
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="%d/%m/%Y")
df[df["Ship Date"] > df["Order Date"]][["Order Date", "Ship Date", "Sales"]].sort_values("Ship Date")

     Order Date  Ship Date    Sales
7180 2014-01-06 2014-01-07   12.780
7980 2014-01-03 2014-01-07   16.448
5327 2014-01-06 2014-01-08   19.440
739  2014-01-04 2014-01-08   11.784
740  2014-01-04 2014-01-08  272.736
...         ...        ...      ...
573  2017-12-28 2018-01-04   14.850
571  2017-12-28 2018-01-04   13.960
4239 2017-12-29 2018-01-04  209.700
645  2017-12-30 2018-01-05  209.300
5131 2017-12-29 2018-01-05  101.120

[9475 rows x 3 columns]

In [13]:
#Q10
df[(df["Sales"] >= 100) & (df["Sales"]<= 500)][["State", "Category", "Sales", "Profit"]].sort_values("Profit",ascending= False)

             State         Category    Sales     Profit
9696      Michigan  Office Supplies  491.550   240.8595
6922       Alabama  Office Supplies  491.550   240.8595
4029     Louisiana       Technology  479.970   239.9850
8877    New Jersey       Technology  480.000   225.6000
7557       Indiana  Office Supplies  497.940   224.0730
...            ...              ...      ...        ...
1681  Pennsylvania       Technology  399.540  -559.3560
7422  Pennsylvania       Technology  449.100  -643.7100
6262      Illinois  Office Supplies  442.372  -729.9138
1995         Texas  Office Supplies  294.620  -766.0120
4820         Texas  Office Supplies  463.248 -1181.2824

[2606 rows x 4 columns]

LEVEL 2

In [14]:
#Q1
df1 = df.groupby("State").agg(Total_sales=("Sales","sum"), Avg_profit=("Profit","mean") ).reset_index()
df1[df1["Avg_profit"] < 0].sort_values("Total_sales", ascending=False).head()

           State  Total_sales  Avg_profit
41         Texas  170188.0458  -26.121174
36  Pennsylvania  116511.9140  -26.507598
8        Florida   89473.7080   -8.875461
11      Illinois   80166.1010  -25.625787
33          Ohio   78258.1360  -36.186304

In [15]:
#Q2
df1 = df.groupby("Category").agg(total_sales=("Sales","sum"), total_profit=("Profit","sum")).reset_index()
df1["profit_margin"] = df1["total_profit"] / df1["total_sales"]
df1[df1["profit_margin"] < 0.1].sort_values("profit_margin")

    Category  total_sales  total_profit  profit_margin
0  Furniture  741999.7953    18451.2728       0.024867

In [16]:
#Q3
df1 = df.groupby(["Region","Sub-Category"]).agg(Total_Profit=("Profit", "sum")).reset_index()
df2 = df1.sort_values(["Region","Total_Profit"],ascending=[True,False])
df2.groupby("Region").head(3)

     Region Sub-Category  Total_Profit
6   Central      Copiers    15608.8413
13  Central       Phones    12323.0267
0   Central  Accessories     7251.6306
23     East      Copiers    17022.8418
30     East       Phones    12314.6860
20     East      Binders    11267.9346
47    South       Phones    10767.2753
34    South  Accessories     7004.5424
39    South       Chairs     6612.0893
57     West      Copiers    19327.2351
51     West  Accessories    16484.5983
54     West      Binders    16096.8016

Rank

In [17]:
df1 = (df.groupby(["Region", "Sub-Category"]).agg(Total_Profit=("Profit", "sum")).reset_index())

df2 = df1.sort_values(["Region", "Total_Profit"], ascending=[True, False])

df2["Rank"] = df2.groupby("Region")["Total_Profit"].rank(method="dense", ascending=False)

df2[df2["Rank"] <= 3]

     Region Sub-Category  Total_Profit  Rank
6   Central      Copiers    15608.8413   1.0
13  Central       Phones    12323.0267   2.0
0   Central  Accessories     7251.6306   3.0
23     East      Copiers    17022.8418   1.0
30     East       Phones    12314.6860   2.0
20     East      Binders    11267.9346   3.0
47    South       Phones    10767.2753   1.0
34    South  Accessories     7004.5424   2.0
39    South       Chairs     6612.0893   3.0
57     West      Copiers    19327.2351   1.0
51     West  Accessories    16484.5983   2.0
54     West      Binders    16096.8016   3.0

In [18]:
#Q4
df1 = df.groupby("Segment").agg(Average_discount=("Discount","mean"), Average_profit=("Profit","mean")).reset_index()
df1.sort_values(["Average_discount","Average_profit"], ascending=[False, True])

       Segment  Average_discount  Average_profit
1    Corporate          0.158228       30.456667
0     Consumer          0.158141       25.836873
2  Home Office          0.147128       33.818664

In [19]:
#Q5
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["year"]=df["Order Date"].dt.year
df1= df.groupby("year").agg(total_sales=("Sales","sum"), total_profit=("Profit","sum")).reset_index()
df1

   year  total_sales  total_profit
0  2014  484247.4981    49543.9741
1  2015  470532.5090    61618.6037
2  2016  609205.5980    81795.1743
3  2017  733215.2552    93439.2696

In [20]:
df1["p_year"]= df1["year"]-1
df2 = df1
df2

   year  total_sales  total_profit  p_year
0  2014  484247.4981    49543.9741    2013
1  2015  470532.5090    61618.6037    2014
2  2016  609205.5980    81795.1743    2015
3  2017  733215.2552    93439.2696    2016

In [21]:
df3 = pd.merge(df1,df2,left_on="year",right_on="p_year", how="right")
df3

,year_x,total_sales_x,total_profit_x,p_year_x,year_y,total_sales_y,total_profit_y,p_year_y
0,NaN,NaN,NaN,NaN,2014,484247.4981,49543.9741,2013
1,2014.0,484247.4981,49543.9741,2013.0,2015,470532.5090,61618.6037,2014
2,2015.0,470532.5090,61618.6037,2014.0,2016,609205.5980,81795.1743,2015
3,2016.0,609205.5980,81795.1743,2015.0,2017,733215.2552,93439.2696,2016

In [22]:
df3["YOY"]= round(((df3["total_sales_y"]-df3["total_sales_x"])/(df3["total_sales_x"]))*100,2)
df3[["year_y","total_sales_y","YOY","total_profit_y"]]

   year_y  total_sales_y    YOY  total_profit_y
0    2014    484247.4981    NaN      49543.9741
1    2015    470532.5090  -2.83      61618.6037
2    2016    609205.5980  29.47      81795.1743
3    2017    733215.2552  20.36      93439.2696

In [23]:
#Q6
df1  = df.groupby("City").agg(total_sales=("Sales","sum"), total_profit=("Profit","sum")).reset_index()

s_75 = df1["total_sales"].quantile(0.75)
df1[(df1["total_sales"] > s_75) & (df1["total_profit"]<0)].sort_values("total_sales")

                 City  total_sales  total_profit
2               Akron    2729.9860     -186.6356
413          Rockford    3166.2280    -1149.5078
281            Marion    3369.3460     -380.3623
379             Plano    3530.3746     -383.0554
137           El Paso    3546.0640     -179.9007
92   Colorado Springs    3694.0090     -956.6841
8            Amarillo    3773.0628     -387.9683
228         Knoxville    3928.1660    -1165.0755
293              Mesa    4037.7400     -559.2314
485            Toledo    4466.0530     -339.9968
488              Troy    4507.0910     -544.1518
420        Round Rock    4854.0528    -1183.4313
153   Fort Lauderdale    4929.5325     -161.3551
473             Tampa    5196.0805     -325.2366
238          Lakeland    5606.8865     -188.6365
289           Memphis    5942.3410    -1479.0400
25             Austin    6057.9820      -20.3938
323         Nashville    6070.8630     -837.4908
489            Tucson    6313.0160      -64.9668
86          Cleveland    6346.1850     -848.0079
295             Miami    8673.0745    -1150.3704
241         Lancaster    9891.4640    -7239.0684
96            Concord   10542.4020     -718.6389
375           Phoenix   11000.2570    -2790.8832
24             Aurora   11656.4780    -2691.7386
120            Denver   12198.7930     -244.9200
267        Louisville   12345.8060    -1430.3129
74          Charlotte   13693.3390     -429.7824
109            Dallas   20131.9322    -2846.5257
60         Burlington   21668.0820    -3622.8772
434       San Antonio   21843.5280    -7299.0502
216      Jacksonville   44713.1830    -2323.8350
80            Chicago   48539.5410    -6654.5688
207           Houston   64504.7604   -10153.5485
374      Philadelphia  109077.0130   -13837.7674

In [24]:
#Q7
df1=df[df["Discount"] > 0.4]
df2 = df1.groupby(["Category","Sub-Category"]).agg(total_orders=("Order ID","count"), T_discount=("Discount","sum")).reset_index()
df2["rate_proxy"] = (df2["T_discount"] / df2["total_orders"])*100
df2[df2["rate_proxy"]>= 30].sort_values("rate_proxy",ascending=False).head(10)

          Category Sub-Category  total_orders  T_discount  rate_proxy
3  Office Supplies   Appliances            67       53.60   80.000000
4  Office Supplies      Binders           613      452.40   73.800979
5       Technology     Machines            35       22.10   63.142857
1        Furniture  Furnishings           138       82.80   60.000000
0        Furniture    Bookcases            33       19.50   59.090909
2        Furniture       Tables            47       22.95   48.829787

In [25]:
#Q8
df1 = df.groupby("Customer Name").agg(Order_Count = ("Order ID","count"),Avg_profit=("Profit","mean")).reset_index()
df1[(df1["Order_Count"]>5) & (df1["Avg_profit"]<0)].sort_values("Avg_profit")

         Customer Name  Order_Count  Avg_profit
165      Cindy Stewart            9 -736.265500
307     Grant Thornton            6 -684.776483
693     Sharelle Roach            9 -370.434933
477        Luke Foster           16 -223.998562
329      Henry Goldwyn           17 -164.586088
..                 ...          ...         ...
21        Alex Grayson            9   -0.570789
522  Michael Dominguez            8   -0.505038
579      Odella Nelson           15   -0.392600
7          Adrian Hane           16   -0.144662
593         Paul Lucas            8   -0.094088

[136 rows x 3 columns]

In [26]:
#Q9
df["Delay"] = df["Ship Date"]-df["Order Date"]
df[df["Delay"]> "5 days"].sort_values("Delay", ascending= False)[["Ship Date","Order Date","Delay"]]

      Ship Date Order Date  Delay
3    2015-10-18 2015-10-11 7 days
7184 2017-08-24 2017-08-17 7 days
7204 2015-09-17 2015-09-10 7 days
7188 2017-08-24 2017-08-17 7 days
3395 2017-07-08 2017-07-01 7 days
...         ...        ...    ...
3742 2016-01-21 2016-01-15 6 days
3741 2016-01-21 2016-01-15 6 days
3728 2016-06-11 2016-06-05 6 days
3727 2016-06-11 2016-06-05 6 days
9985 2015-05-23 2015-05-17 6 days

[1824 rows x 3 columns]

In [27]:
#Q10
df1 = df.groupby("State").agg(total_sale=("Sales","sum"), total_profit=("Profit","sum"), no_of_orders=("Order ID","count")).reset_index()
df1.describe()

          total_sale  total_profit  no_of_orders
count      49.000000     49.000000     49.000000
mean    46881.650210   5844.837178    203.959184
std     80776.294534  17468.637186    351.201269
min       919.910000 -25729.356300      1.000000
25%      7464.930000    230.149700     37.000000
50%     22205.150000   2196.102300     82.000000
75%     49095.840000   7285.629300    184.000000
max    457687.631500  76381.387100   2001.000000

In [28]:
sales_med = df1["total_sale"].median()
profit_med = df1["total_profit"].median()
def category(x,y):
  if x > sales_med and y > profit_med:
    return "High Sales – High Profit"
  elif x > sales_med and y < profit_med:
    return "High Sales – Low Profit"
  elif x < sales_med and y > profit_med:
    return "Low Sales – High Profit"
  else:
    return "Low Sales – Low Profit"
df1["Category"] = df1.apply(lambda x: category(x["total_sale"], x["total_profit"]),axis=1)
df1

,State,total_sale,total_profit,no_of_orders,Category
0,Alabama,19510.6400,5786.8253,61,Low Sales – High Profit
1,Arizona,35282.0010,-3427.9246,224,High Sales – Low Profit
2,Arkansas,11678.1300,4008.6871,60,Low Sales – High Profit
3,California,457687.6315,76381.3871,2001,High Sales – High Profit
4,Colorado,32108.1180,-6527.8579,182,High Sales – Low Profit
5,Connecticut,13384.3570,3511.4918,82,Low Sales – High Profit
6,Delaware,27451.0690,9977.3748,96,High Sales – High Profit
7,District of Columbia,2865.0200,1059.5893,10,Low Sales – Low Profit
8,Florida,89473.7080,-3399.3017,383,High Sales – Low Profit
9,Georgia,49095.8400,16250.0433,184,High Sales – High Profit
10,Idaho,4382.4860,826.7231,21,Low Sales – Low Profit
11,Illinois,80166.1010,-12607.8870,492,High Sales – Low Profit
12,Indiana,53555.3600,18382.9363,149,High Sales – High Profit
13,Iowa,4579.7600,1183.8119,30,Low Sales – Low Profit
14,Kansas,2914.3100,836.4435,24,Low Sales – Low Profit
15,Kentucky,36591.7500,11199.6966,139,High Sales – High Profit
16,Louisiana,9217.0300,2196.1023,42,Low Sales – Low Profit
17,Maine,1270.5300,454.4862,8,Low Sales – Low Profit
18,Maryland,23705.5230,7031.1788,105,High Sales – High Profit
19,Massachusetts,28634.4340,6785.5016,135,High Sales – High Profit
20,Michigan,76269.6140,24463.1876,255,High Sales – High Profit
21,Minnesota,29863.1500,10823.1874,89,High Sales – High Profit
22,Mississippi,10771.3400,3172.9762,53,Low Sales – High Profit
23,Missouri,22205.1500,6436.2105,66,Low Sales – Low Profit
24,Montana,5589.3520,1833.3285,15,Low Sales – Low Profit
25,Nebraska,7464.9300,2037.0942,38,Low Sales – Low Profit
26,Nevada,16729.1020,3316.7659,39,Low Sales – High Profit
27,New Hampshire,7292.5240,1706.5028,27,Low Sales – Low Profit
28,New Jersey,35764.3120,9772.9138,130,High Sales – High Profit
29,New Mexico,4783.5220,1157.1161,37,Low Sales – Low Profit
30,New York,310876.2710,74038.5486,1128,High Sales – High Profit
31,North Carolina,55603.1640,-7490.9122,249,High Sales – Low Profit
32,North Dakota,919.9100,230.1497,7,Low Sales – Low Profit
33,Ohio,78258.1360,-16971.3766,469,High Sales – Low Profit
34,Oklahoma,19683.3900,4853.9560,66,Low Sales – High Profit
35,Oregon,17431.1500,-1190.4705,124,Low Sales – Low Profit
36,Pennsylvania,116511.9140,-15559.9603,587,High Sales – Low Profit
37,Rhode Island,22627.9560,7285.6293,56,High Sales – High Profit
38,South Carolina,8481.7100,1769.0566,42,Low Sales – Low Profit
39,South Dakota,1315.5600,394.8283,12,Low Sales – Low Profit
40,Tennessee,30661.8730,-5341.6936,183,High Sales – Low Profit
41,Texas,170188.0458,-25729.3563,985,High Sales – Low Profit
42,Utah,11220.0560,2546.5335,53,Low Sales – High Profit
43,Vermont,8929.3700,2244.9783,11,Low Sales – High Profit
44,Virginia,70636.7200,18597.9504,224,High Sales – High Profit
45,Washington,138641.2700,33402.6517,506,High Sales – High Profit
46,West Virginia,1209.8240,185.9216,4,Low Sales – Low Profit
47,Wisconsin,32114.6100,8401.8004,110,High Sales – High Profit
48,Wyoming,1603.1360,100.1960,1,Low Sales – Low Profit

In [29]:
df.dtypes

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
Country                   object
City                      object
State                     object
Postal Code              float64
Region                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
year                       int32
Delay            timedelta64[ns]
dtype: object

In [30]:
df["Region" ].unique()

array(['South', 'West', 'Central', 'East'], dtype=object)

In [31]:
df["Sub-Category"].unique()

array(['Bookcases', 'Chairs', 'Labels', 'Tables', 'Storage',
       'Furnishings', 'Art', 'Phones', 'Binders', 'Appliances', 'Paper',
       'Accessories', 'Envelopes', 'Fasteners', 'Supplies', 'Machines',
       'Copiers'], dtype=object)

In [32]:
df["Segment"].unique()

array(['Consumer', 'Corporate', 'Home Office'], dtype=object)